/**
 * Proverbes et dictons français traditionnels : anonymes, courts, de tradition orale. Ce sont les phrases
 * du jour proposées d'office ; l'utilisateur ajoute les siennes dans « Mes citations » (voir model.ts).
 * Ne pas y ajouter de citations d'auteurs.
 */
export const PROVERBS: readonly string[] = [
  'Petit à petit, l’oiseau fait son nid.',
  'Après la pluie, le beau temps.',
  'Rome ne s’est pas faite en un jour.',
  'Qui va doucement va sûrement.',
  'Aide-toi, le ciel t’aidera.',
  'L’union fait la force.',
  'Chaque chose en son temps.',
  'Il n’est jamais trop tard pour bien faire.',
  'Mieux vaut tard que jamais.',
  'Tout vient à point à qui sait attendre.',
  'À cœur vaillant, rien d’impossible.',
  'Quand on veut, on peut.',
  'La nuit porte conseil.',
  'Pierre qui roule n’amasse pas mousse.',
  'Les petits ruisseaux font les grandes rivières.',
  'Une hirondelle ne fait pas le printemps.',
  'Il faut battre le fer tant qu’il est chaud.',
  'L’appétit vient en mangeant.',
  'Les bons comptes font les bons amis.',
  'Après l’effort, le réconfort.',
  'Tout ce qui brille n’est pas or.',
  'L’habit ne fait pas le moine.',
  'Mieux vaut prévenir que guérir.',
  'Qui se ressemble s’assemble.',
  'À chaque jour suffit sa peine.',
  'Il n’y a pas de fumée sans feu.',
  'Un homme averti en vaut deux.',
  'C’est en forgeant qu’on devient forgeron.',
  'L’erreur est humaine.',
  'À l’impossible, nul n’est tenu.',
  'Mieux vaut être seul que mal accompagné.',
  'Loin des yeux, loin du cœur.',
  'Pas de nouvelles, bonne nouvelle.',
  'Le mieux est l’ennemi du bien.',
  'Qui ne risque rien n’a rien.',
  'La fortune sourit aux audacieux.',
  'La parole est d’argent, le silence est d’or.',
  'Rira bien qui rira le dernier.',
  'Chat échaudé craint l’eau froide.',
  'Il ne faut pas courir deux lièvres à la fois.',
  'Il faut tourner sept fois sa langue dans sa bouche avant de parler.',
  'Chacun son métier, les vaches seront bien gardées.',
  'Tous les chemins mènent à Rome.',
  'Qui ne dit mot consent.',
  'L’argent ne fait pas le bonheur.',
  'Fais ce que dois, advienne que pourra.',
  'Il n’est si longue nuit qui n’ait son jour.',
  'Il n’y a que le premier pas qui coûte.',
  'Tout est bien qui finit bien.',
  'Plus on est de fous, plus on rit.',
  'L’espoir fait vivre.',
  'Il faut de tout pour faire un monde.',
  'Les goûts et les couleurs ne se discutent pas.',
  'Toute peine mérite salaire.',
  'Le mauvais ouvrier a toujours de mauvais outils.',
  'Qui dort dîne.',
  'Le jeu n’en vaut pas la chandelle.',
  'Il ne faut pas mettre tous ses œufs dans le même panier.',
  'Quand le chat n’est pas là, les souris dansent.',
  'Les jours se suivent et ne se ressemblent pas.',
  'Le temps guérit toutes les blessures.',
  'Tant va la cruche à l’eau qu’à la fin elle se casse.',
  'Chassez le naturel, il revient au galop.',
  'À bon chat, bon rat.',
  'Bonne renommée vaut mieux que ceinture dorée.',
  'Les paroles s’envolent, les écrits restent.',
  'Tout nouveau, tout beau.',
  'Qui veut aller loin ménage sa monture.',
  'Qui ne tente rien n’a rien.',
  'L’avenir appartient à ceux qui se lèvent tôt.',
  'Il n’est pire eau que l’eau qui dort.',
  'Les cordonniers sont les plus mal chaussés.',
  'On reconnaît l’arbre à ses fruits.',
  'À quelque chose malheur est bon.',
  'Il faut que jeunesse se passe.',
  'Si jeunesse savait, si vieillesse pouvait.',
  'La nuit, tous les chats sont gris.',
  'Dans le doute, abstiens-toi.',
  'Bien faire et laisser dire.',
  'Qui vivra verra.',
  'Demain est un autre jour.',
  'Mieux vaut en rire qu’en pleurer.',
  'Il n’y a pas de sot métier.',
  'C’est au pied du mur qu’on voit le maçon.',
  'Avec des si, on mettrait Paris en bouteille.',
  'Il y a un temps pour tout.',
  'Les apparences sont trompeuses.',
  'Mieux vaut donner que recevoir.',
  'Le soleil luit pour tout le monde.',
  'Noël au balcon, Pâques au tison.',
  'En avril, ne te découvre pas d’un fil ; en mai, fais ce qu’il te plaît.',
  'Rouge le soir, espoir ; rouge le matin, chagrin.',
  'S’il pleut à la Saint-Médard, il pleut quarante jours plus tard.',
  'Petite pluie abat grand vent.',
  'Un tiens vaut mieux que deux tu l’auras.',
  'Il ne faut jurer de rien.',
  'Les petits cadeaux entretiennent l’amitié.',
  'Tel est pris qui croyait prendre.',
  'Ventre affamé n’a point d’oreilles.',
  'Les chiens aboient, la caravane passe.',
  'Un travail bien commencé est à moitié fait.',
  'On récolte ce que l’on sème.',
  'Une de perdue, dix de retrouvées.',
  'Chaque médaille a son revers.',
  'La curiosité est un beau défaut.',
  'Contentement passe richesse.',
  'On ne change pas une équipe qui gagne.',
  'Mieux vaut un petit chez-soi qu’un grand chez les autres.',
];
